# Generated by Django 5.1.6 on 2025-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
    ]
