# Generated by Django 5.1.6 on 2025-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_event_info_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('grade1_price', models.FloatField()),
                ('grade2_price', models.FloatField()),
                ('grade3_price', models.FloatField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
