# Generated by Django 5.1.6 on 2025-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_requestedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
